Repository netboxlabs/diode-sdk-go, pull requests merged in 2024-12, with the labels that each got.

#16 chore: enable gofumpt linter
  .github/golangci.yaml
  Makefile
Labels: internal, go

#17 chore: bump golang.org/x/*
  go.mod
  go.sum
Labels: dependencies

#19 chore: go toolchain version + github actions commit hash pinning
  .github/workflows/lint.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  go.mod
Labels: github-actions, dependencies
