Repository netboxlabs/diode-sdk-go, pull requests merged in 2025-04, with the labels that each got.

#22 fix: include several missing many-many references
  diode/ingester.go
  diode/v1/diodepb/ingester.pb.go
  diode/v1/diodepb/ingester.pb.validate.go
  diode/v1/diodepb/ingester_grpc.pb.go
Labels: go

#24 feat: replace api key with oauth2
  Makefile
  README.md
  diode/client.go
  diode/client_test.go
  examples/main.go
Labels: documentation, internal, go, markdown

#27 perf: update README
  README.md
Labels: documentation, markdown

#29 🚀 release: 1.0.0
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/01-feature_request.yaml
  .github/ISSUE_TEMPLATE/02-bug_report.yaml
  .github/ISSUE_TEMPLATE/03-documentation_change.yaml
  .github/ISSUE_TEMPLATE/config.yaml
  .github/golangci.yaml
  .github/workflows/lint.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  Makefile
  README.md
  diode/client.go
  diode/client_test.go
  diode/ingester.go
  diode/ingester_test.go
  diode/v1/diodepb/ingester.pb.go
  diode/v1/diodepb/ingester.pb.validate.go
  diode/v1/diodepb/ingester_grpc.pb.go
  examples/main.go
  go.mod
  go.sum
  internal/cmd/codegen/main.go
  internal/codegen/codegen.go
Labels: documentation, github-actions, internal, dependencies, go, markdown, github-templates
